services:
  app:
    build:
      context: .
    command: bash -c "poetry run alembic upgrade head & poetry run python main.py"
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - note_net

  db:
    image: postgres:15
    container_name: db
    volumes:
      - .:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - .env
    networks:
      - note_net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - note_net

networks:
    note_net:
      name: note_net