"""Added note,tag tables

Revision ID: 36918efa5775
Revises: 41d9ada604e4
Create Date: 2024-09-16 13:14:36.409797
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '36918efa5775'
down_revision: Union[str, None] = '41d9ada604e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'notes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'notes_tags_table_association',
        sa.Column('notes_id', sa.Integer(), nullable=False),
        sa.Column('tags_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['notes_id'],
            ['notes.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tags_id'],
            ['tags.id'],
        ),
        sa.PrimaryKeyConstraint('notes_id', 'tags_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes_tags_table_association')
    op.drop_table('tags')
    op.drop_table('notes')
    # ### end Alembic commands ###
